import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 部署到 vault002 插件目录
const deploy = () => {
  const targetVault = process.env.ALL2MD_VAULT || "E:\\Obsidian\\vault002-outup-others";
  const pluginDir = path.join(targetVault, ".obsidian", "plugins", "all2md");
  try {
    fs.mkdirSync(pluginDir, { recursive: true });
    const artifacts = ["main.js", "manifest.json", "styles.css"];
    for (const f of artifacts) {
      if (fs.existsSync(f)) {
        fs.copyFileSync(f, path.join(pluginDir, f));
        console.log(`[deploy] ${f} -> ${pluginDir}`);
      }
    }
    // PDF worker：自 2026-08-24 起 worker 内联进 main.js（globalThis.pdfjsWorker 注入，
    // 见 pdf-converter.ts 注释），不再需要独立部署 pdf.worker.mjs
    console.log(`[deploy] synced to ${pluginDir}`);
  } catch (e) {
    console.error(`[deploy] failed: ${e.message}`);
  }
};

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  platform: "node",
  target: "ES6",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

if (prod) {
  esbuild
    .build(buildOptions)
    .then(() => deploy())
    .catch(() => process.exit(1));
} else {
  esbuild
    .context(buildOptions)
    .then(async (context) => {
      context.onEnd(() => deploy());
      await context.watch();
      deploy(); // 首次立即同步一次
      console.log("Watching for changes...");
    })
    .catch(() => process.exit(1));
}
