import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// mammoth 的 package.json browser 字段不会被 esbuild 应用到包内相对路径引用，
// 导致 Node 版 files.js / unzip.js（含 require("fs")）被打进产物。
// 这里用插件显式把这两个内部引用重定向到浏览器实现（上架审查整改，2026-09-28）。
const mammothBrowserPlugin = {
  name: "mammoth-browser-redirect",
  setup(build) {
    build.onResolve({ filter: /^\.\/files$/ }, (args) => {
      if (args.importer.includes("node_modules" + path.sep + "mammoth")) {
        return { path: path.resolve("node_modules/mammoth/browser/docx/files.js") };
      }
      return null;
    });
    build.onResolve({ filter: /^\.\/unzip$/ }, (args) => {
      if (args.importer.includes("node_modules" + path.sep + "mammoth")) {
        return { path: path.resolve("node_modules/mammoth/browser/unzip.js") };
      }
      return null;
    });
  },
};

// 部署到 vault002 插件目录
const deploy = () => {
  const targetVault = process.env.ALLTOMD_VAULT || "E:\\Obsidian\\vault002-outup-others";
  const pluginDir = path.join(targetVault, ".obsidian", "plugins", "alltomd");
  try {
    fs.mkdirSync(pluginDir, { recursive: true });
    const artifacts = ["main.js", "manifest.json", "styles.css"];
    for (const f of artifacts) {
      if (fs.existsSync(f)) {
        fs.copyFileSync(f, path.join(pluginDir, f));
        console.log(`[deploy] ${f} -> ${pluginDir}`);
      }
    }
    // PDF worker：自 2026-08-24 起 worker 内联进 main.js（globalThis.pdfjsWorker 注入，
    // 见 pdf-converter.ts 注释），不再需要独立部署 pdf.worker.mjs
    console.log(`[deploy] synced to ${pluginDir}`);
  } catch (e) {
    console.error(`[deploy] failed: ${e.message}`);
  }
};

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  platform: "node",
  mainFields: ["browser", "module", "main"],
  // immediate 包（jszip -> lie -> immediate 依赖链）特性检测里含
  // document.createElement("script")，社区审查会扫产物里的 script 注入标记。
  // jszip 的 browser 字段会把入口重定向到预打包的 dist/jszip.min.js，
  // 里面内联了完整的 immediate 特性检测代码，alias 拦不到，所以连入口一起改指到 lib/。
  // 本 shim 用 Promise 微任务提供等价的「尽快异步执行」语义（上架审查整改，2026-09-28）。
  alias: {
    immediate: path.resolve("src/shims/immediate.js"),
    setimmediate: path.resolve("src/shims/setimmediate.js"),
    jszip: path.resolve("node_modules/jszip/lib/index.js"),
  },
  target: "ES6",
  // 产物压缩：体积要控制在 5MB 以内（Obsidian Sync Standard 同步上限，社区审查会警告）
  minify: prod,
  minifyWhitespace: prod,
  minifyIdentifiers: prod,
  minifySyntax: prod,
  keepNames: true,
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  plugins: [mammothBrowserPlugin],
  outfile: "main.js",
};

if (prod) {
  esbuild
    .build(buildOptions)
    .then(() => deploy())
    .catch(() => process.exit(1));
} else {
  esbuild
    .context(buildOptions)
    .then(async (context) => {
      context.onEnd(() => deploy());
      await context.watch();
      deploy(); // 首次立即同步一次
      console.log("Watching for changes...");
    })
    .catch(() => process.exit(1));
}
